/* eslint-disable */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}', 'node_modules/flowbite-react/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      minWidth: {
        onehundred: '100%',
        ninty: '90%',
        eighty: '80%',
        sixty: '60%',
        fifty: '50%',
        forty: '40%',
        thirtythree: ': 33.333333%',
      },
      maxWidth: {
        onehundred: '100%',
        ninty: '90%',
        sixty: '60%',
        forty: '40%',
        eighty: '80%',
        fifty: '50%',
        fortyFive: '45%',
        thirtythree: ': 33.333333%',
      },
      height: {
        onehundred: '100%',
        nintyFive: '95%',
        ninty: '90%',
        eighty: '80%',
        seventy: '70%',
        sixty: '60%',
        fifty: '50%',
        fortyFive: '45%',
        forty: '40%',
        thirty: '30%',
        twenty: '20%',
      },
      width: {
        onehundred: '100%',
        nintyfive: '94%',
        nintyfour: '94%',
        nintythree: '93%',
        ninty: '90%',
        eightyFive: '85%',
        eighty: '80%',
        seventy: '70%',
        sixty: '60%',
        fifty: '50%',
        forty: '40%',
        thirty: '30%',
      },
      top: {
        ninty: '90%',
        forty: '40%',
        eighty: '80%',
        fifty: '50%',
      },
      maxHeight: {
        onehundred: '100%',
        ninty: '90%',
        sixty: '60%',
        forty: '40%',
        eighty: '80%',
        fifty: '50%',
        fortyFive: '45%',
        thirtythree: ': 33.333333%',
      },
      minHeight: {
        onehundred: '100%',
        ninty: '90%',
        sixty: '60%',
        forty: '40%',
        eighty: '80%',
        fifty: '50%',
        fortyFive: '45%',
        thirtythree: ': 33.333333%',
      },
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
      fontFamily: {
        roboto: ['Roboto', 'sans-serif'],
      },
    },
  },
  plugins: [require('flowbite/plugin'), require('@tailwindcss/line-clamp')],
};
